#!/usr/bin/env bash
# Displaying bad luck numbers
counter=1
while [ $counter -le 10 ]
do
	echo "Best School"
	if [ $counter = 4 ]
	then
		echo "bad luck"
	elif [ $counter = 8 ]
	then 
		echo "good luck"
	else 
		echo "Best School"
	fi
done
