#!/usr/bin/env bash
# Displaying the school file 

file=school

if [ -e "$file" ]
then
	echo "School file exist"

if [ -s "$file" ]
then 
	echo "School file is not empty"

else 
	echo "School file is empty"

fi

 if [ -f "$file" ]
 then 
	echo "School is a regular file"
 
else 
	echo "School file does not exist"

fi
fi

