#!/usr/bin/env bash
#

sudo touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid

while :
do
echo "To infinity and beyond "

trap 'echo "I hate the kill command"' SIGTERM

trap 'echo "Y U no love me?!"' SIGINT

sudo rm -r "/var/run/myscript.pid" SIGQUIT ; exit

done
