#!/usr/bin/env bash
#

sudo touch /var/run/myscript.pid
sudo bash -c ' echo $$ > /var/run/myscript.pid'

while :
do
echo "To infinity and beyond "

trap 'echo "I hate the kill command";sudo rm -r "/var/run/myscript.pid"' SIGTERM

trap 'echo "Y U no love me?!"' SIGINT

trap 'sudo rm -r "/var/run/myscript.pid";exit' SIGQUIT

done
